name = "cookout-menu-platform"
compatibility_date = "2026-09-21"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "cookout-menu"
database_id = "fb7dd4ba-7c20-401e-a81a-40d425ad5f96"
